logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.boot.actuate.endpoint.web: WARN
    com.nimbusds: DEBUG
server:
  port: ${SERVER_PORT:8082}
  ssl:
    enabled: ${SSL_ENABLED:true}
    key-store: file:${CONFIG_PATH:/repo/vscode/oidc-test/config}/keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: springboot
  forward-headers-strategy: framework
  use-forward-headers: true
spring:
  security:
    oauth2:
      client:
        registration:
          demo:
            client-id: demo-client-id
            client-secret: demo-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          demo:
            authorization-uri: ${OIDC_AUTHORIZATION_URI:https://localhost/backend/authorize}
            token-uri: ${OIDC_TOKEN_URI:https://localhost/backend/token}
            user-info-uri: ${OIDC_USERINFO_URI:https://localhost/backend/userinfo}
            jwk-set-uri: ${OIDC_JWKS_URI:https://localhost/backend/.well-known/jwks.json}
            user-name-attribute: sub
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
